### ISSUE TITLE
Package runs code on import

### ISSUE THREAD

**Issue by AJNeufeld** [pjz/mhi#23]
# The Ask

If possible, can you alter your code such that merely executing `import mhi` does not run code?

The smallest change I can envision is:

```diff
-cfgdir = os.environ.get('HOME', '')
-config = ConfigObj(infile=f"{cfgdir}/.mhirc", create_empty=True)
-state = ConfigObj(infile=f"{cfgdir}/.mhistate", create_empty=True)

 def _cmd_dispatch(args):
+    global config, state
+    cfgdir = os.environ.get('HOME', '')
+    config = ConfigObj(infile=f"{cfgdir}/.mhirc", create_empty=True)
+    state = ConfigObj(infile=f"{cfgdir}/.mhistate", create_empty=True)
     try:
```

Perhaps better could be to move the vast majority of the code from `__init__.py` into `__main__.py`, or perhaps to a new `main.py` file, but that may be more work that you wish to do.

# The Issue

Attempting to import `mhi.pscad`,  `mhi.enerplot`, `mhi.cosim`, `mhi.psout`, or `mhi.xml` (packages by Manitoba Hydro International, aka MHI) implicitly cause `mhi` to be imported first, if it is installed.  If it is not installed, the `mhi.` prefix is treated as a "namespace" package - no import of `mhi` is attempted.  For the vast majority of the time, your Mail Handler from IMAP package and the Manitoba Hydro International packages work together without conflict.

Except ...

> Customer Issue:
> > I am receiving the error  “PermissionError: [Errno 13] Permission denied: '/.mhirc'” when attempting to run a Python project.

... some of our users accidentally install your `mhi` package, along with `mhi.pscad`, and _if they do not have the HOME environment set_ (angry stare at Microsoft for deciding to use `USERPROFILE` instead of `HOME`) _and cannot write to the root directory_, then importing our package fails in `import mhi.pscad` inside the implicit (and therefor, uncatchable) `import mhi`.

# Alternate

I suppose another alternative would be to fallback to `os.environ.get('USERPROFILE')` on Windows, if `HOME` is not set.  At least then the file creation would likely succeed.

Thanks, in advance, 
   [Arthur](https://pypi.org/user/AJNeufeld/)

**Comment by pjz** [comment]
Another alternative would be to have your users install mhi using pipx so it gets its own virtualenv, which might also solve their problem.

But I'll also see what I can do about reorganizing a little bit.

**Comment by pjz** [comment]
Should be fixed in 4c265deea7f23a57fbc66185158d09db679477e6 .  Hope this helps.

**Comment by AJNeufeld** [comment]
Wow!  You went above and beyond.  Thank-you so much!

I fear you introduced a bug, though.  In `pyproject.toml`,  you have `mhiWrap = 'mhi:cmd_main'`, and `cmd_main()` calls `_cmd_dispatch(...)` without setting the `state` or `config` globals,  So I _think_ your "wrapped" scripts now won't work.  (Which is why I proposed setting those globals in `_cmd_dispatch()` ... you'd only need to set them in the one place, instead in both `main` and `cmd_main`.)

**Comment by pjz** [comment]
Should be solved in https://github.com/pjz/mhi/releases/tag/0.8.6
