### ISSUE TITLE
mhi fails with Python 3.7 (and earlier)

### ISSUE THREAD

**Issue by AJNeufeld** [pjz/mhi#9]
When installed in Python 3.7, importing `mhi` results in an f-string error:

```
C:\Users\aneufeld\Documents> py
Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import mhi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<fstring>", line 1
    (env_date=)
             ^
SyntaxError: invalid syntax
>>> ^Z
```

While f-strings are supported in Python 3.7, the `f"{variable=}"` shortcut for `f"variable={variable}"` is a Python 3.8+ feature.

**Comment by pjz** [comment]
Fixed in https://github.com/pjz/mhi/commit/1035a5972f9f18fbd20ba6cbd5ff623dabfc1d08 ; release 0.8.2

**Comment by AJNeufeld** [comment]
First, thanks for your quick fix of the issue!

Second, I see now: you had specified `'Programming Language :: Python :: 3.8'` in the `classifiers` list.

From [Packaging and distributing projects](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/) (emphasis mine):
> Although the list of classifiers is often used to declare what Python versions a project supports, **this information is only used for searching & browsing projects on PyPI**, not for installing projects. To actually **restrict** what Python versions a project can be installed on, use the **[python_requires](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#python-requires) argument**.

To your `setup.py`, you should added either:
- `python_requires='>=3.7',` since you are using `f"strings"`, or
- `python_requires='>=3.8',` if you want to use `f"{var=}"` variants.

The latter would have properly prevented PIP from installing `mhi-0.8.1` in Python 3.7 environments.  (Without any `python_requires=` line, users can still accidentally add `mhi-0.8.2` into Python 3.6 and earlier, so I recommend a 0.8.3 update.)
